[project]
authors = [
    {name = "Sebastian Stark, Marlon Berlin", email = "cran@users.sourceforge.net, imaginat@users.sourceforge.net"},
    {name = "Stefane Fermigier", email = "sf@abilian.com"},
]
maintainers = [
    {name = "Stefane Fermigier", email = "sf@abilian.com"},
]
license = {text = "BSD"}
requires-python = "<4.0,>=3.9"
dependencies = [
    "tomli>=2.0.0; python_version<'3.11'",
    "tomli-w>=1.0.0",
]
name = "tentakel"
version = "4.0.3"
description = "distributed command execution"
readme = "README.md"

[project.urls]
homepage = "https://github.com/sfermigier/tentakel"

[project.scripts]
tentakel = "tentakel.main:main"

[dependency-groups]
dev = [
    "abilian-devtools<1.0.0,>=0.5.2",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
exclude = ["src/tentakel/tpg.py"]

[tool.pyright]
exclude = [
    '.nox', 'tests', 'sandbox', 'doc', 'scripts', 'tmp', "src/tentakel/tpg.py", "src/tentakel/plugins/rsh.py"
]
include = ["src"]
